### PR TITLE
Update rust version

### PR DESCRIPTION
**Pull request by calebzulawski**

### CODE REVIEW

**Comment by calebzulawski** [comment]
Whoops, we already had the toolchain locked. Thought I hadn't done it yet. Why did we suddenly get the `inline_const` stabilization errors? Maybe something wrong in the CI script

**Comment by programmerjake** [comment]
> Whoops, we already had the toolchain locked. Thought I hadn't done it yet. Why did we suddenly get the `inline_const` stabilization errors? Maybe something wrong in the CI script

because inline consts were stabilized on nightly: https://github.com/rust-lang/rust/pull/104087#issuecomment-2075679329

**Comment by calebzulawski** [comment]
I meant why was I seeing them when we were supposed to be locked to an older toolchain

**Comment by programmerjake** [comment]
> I meant why was I seeing them when we were supposed to be locked to an older toolchain

the updated version uses today's (or yesterday depending on time zones) nightly...I wouldn't call that old. the stabilization PR was merged about a week ago.

**Pull request merged**
