### PR TITLE
Add `abs_diff` function to `SimdInt` and `SimdUint` traits

### PR DESCRIPTION
**Pull request by okaneco**
Implement `abs_diff` for signed and unsigned integer vectors

### CODE REVIEW

**Comment by calebzulawski** [comment]
Thank you! Can you move the test under the macros that generate all of the int/uint tests? That will allow the function to be fuzzed over all the types/lane counts/inputs

**Comment by calebzulawski** [comment]
I think it would be the same as this: https://github.com/rust-lang/portable-simd/blob/283acf44cc889a159483c4805cf29c75d6c13735/crates/core_simd/tests/ops_macros.rs#L553

However, it should be under the signed and unsigned tests, not float.

**Comment by okaneco** [comment]
Thanks, I'll give that a try

**Comment by okaneco** [comment]
Removed the original test file I added
Added the tests to `impl_signed_tests` and `impl_unsigned_tests`

With that advice, it was easy to add the tests

**Comment by calebzulawski** [comment]
Looks good, thanks!

**Pull request merged**
