### PR TITLE
add `Simd::from_slice`

### PR DESCRIPTION
**Pull request by pro465**
this PR adds `Simd::from_slice`. however this needs lots of documentation + (maybe?) optimizations. so it is marked as draft for now

edit:

added docs, and undrafted it

### CODE REVIEW

**Comment by pro465** [comment]
@workingjubilee hopefully this is the end of this PR, as i dont have time to continue work on this PR (because im distracted by new things)

**Review by calebzulawski — APPROVED** [review]

**Comment by pro465** [comment]
@workingjubilee please review the changes 😄

**Comment by workingjubilee** [comment]
Hm. The bizarre failure in const format args is disappointing, and I should probably bring that up with oli or someone, but clearly not your problem.

Right then, going to squash this. Thank you!

**Comment by calebzulawski** [comment]
That's actually a known limitation of const panics.  The formatters are not const!

**Comment by pro465** [comment]
@workingjubilee 

> Right then, going to squash this. 

thank you :>

> Thank you!

always welcome 😄

**Pull request merged**
