### PR TITLE
Fix bitmask vector bit order

### LINKED ISSUE #379: from_bitmask_vector on big-endian calls simd_select_bitmask with the mask at the wrong end of the byte
This code, running on big-endian
```rust
    let bitmask = u8x4::from_array([0b00001101, 0, 0, 0]);
    assert_eq!(
        mask32x4::from_bitmask_vector(bitmask),
        mask32x4::from_array([true, false, true, true]),
    );
```
ends up calling `simd_select_bitmask` with the mask being `0b10110000`. I think that's wrong; for simd_bitmask the mask lives in the least-sigificant bits (see https://github.com/rust-lang/portable-simd/pull/378) so I would expect that `simd_select_bitmask` should be called with `0b00001011`.

This issue is reminiscent of https://github.com/rust-lang/portable-simd/pull/267.

### PR DESCRIPTION
**Pull request by calebzulawski**
Fixes #379

### CODE REVIEW

**Comment by calebzulawski** [comment]
@RalfJung looks good?

**Comment by RalfJung** [comment]
I honestly can't tell, I don't really understand the code in this library. We'll see if this makes the Miri tests pass -- once it propagates into the rustc repository.

I also have no idea what should happen for cases like `N == 12`. Should the first or the last element of the array be the one that is only partially filled? I thought it'd have to be the first element, but then I looked at an example: on little endian, mask `0b001101001001` is the same as `[0b01001001, 0b0011]`, and on big endian the same mask is written `0b100100101100` as a single integer and `[0b10010010, 0b1100]` as an array. Looks like indeed converting the arrays works by reversing the bits in each element, and then fixing up the last element as that is always the one that is "partial".

**Comment by workingjubilee** [comment]
We should explain why this is the correct behavior before we commit it, which means expanding our written spec for `simd_select_bitmask` and `simd_bitmask`.

**Comment by calebzulawski** [comment]
Perhaps we should expose the intrinsics in something like core::intrinsics::simd and use that documentation as the actual semantics

**Comment by RalfJung** [comment]
Any idea when this will be propagated to the rustc repo? :)

**Comment by calebzulawski** [comment]
I just opened https://github.com/rust-lang/rust/pull/121269

**Pull request merged**
