### PR TITLE
rebase "Add some safety comments"

### PR DESCRIPTION
**Pull request by workingjubilee**
This is a partial rebase of https://github.com/rust-lang/portable-simd/pull/182, I just wanted to see if this passes CI now.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Caleb is going to follow up on this so closing.

**Comment by workingjubilee** [comment]
This wound up falling behind again so reopening and rebasing, dropping dated remarks. This keeps not making it in due to changes, but I would rather have half of it than none of it, so I am going to merge this in unless @calebzulawski *strenuously* objects.

**Comment by calebzulawski** [comment]
Yep, might as well merge it.

**Comment by calebzulawski** [comment]
If you want, later today I can rebase the entire original branch, though, since I think this is only a small portion of the original comments.

**Comment by workingjubilee** [comment]
A lot of the ones I dropped need to just be rewritten, so you're welcome to take a swing at that but I don't think it's actually worth thrashing git for it.

**Pull request merged**
