### PR TITLE
feat: add SIMD float math functions (exp, exp2, log, log2, log10, sin…

### PR DESCRIPTION
**Pull request by avhz**
Hi,

In relation to #14, I've added some math functions to check with you if I'm on the right track. 

I simply followed the implementation that was already there for `sqrt`, and for functions that I easily found were already in `intrinsics`. 

Let me know if it's the right way to go :) 

Cheers!

Edit: I manually checked the output values against R, and they were all correct.

### CODE REVIEW

**Comment by calebzulawski** [comment]
Thank you!  I'm now noticing how lacking our tests are in this area, but we can leave that for another day.

**Comment by avhz** [comment]
My pleasure :)

I did notice that too, and I didn't check any special values like `T:MAX`, infinity, etc. 
But I can add tests for these. 

In #14 you mentioned adding intrinsics to the compiler, is this completely done ?

**Comment by calebzulawski** [comment]
I actually thought the intrinsics you used here didn't exist yet.  There might be some still missing, but none stand out to me right now.  Also, I opened #401 to add the tests.

**Comment by calebzulawski** [comment]
After a quick check, the intrinsics that seem to be missing are the `pow`/`powi` intrinsics

**Pull request merged**
