### PR TITLE
Removed need for generic_const_expr in bitmask

### LINKED ISSUE #223: Make `from/to_bitmask` not depend on `generic_const_exprs`
I.e. [these](https://github.com/rust-lang/portable-simd/blob/65cb2c90a0688c110d983a2dbb9932900cd6b5d9/crates/core_simd/src/masks/full_masks.rs#L115) are under `generic_const_exprs` which will take some time to stabilize.

Goal: find a way of re-writing those two functions without using `generic_const_exprs`

### PR DESCRIPTION
**Pull request by jorgecarleitao**
Closes #223

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
I am not sure if this is sufficient - I can't find the tests where we cover compiling under certain feature sets.

**Comment by workingjubilee** [comment]
[Most of it is a simple feature-test on GitHub Actions.](https://github.com/rust-lang/portable-simd/blob/4910274686bcd144228a04d8d4d5dece4c7f5e3d/.github/workflows/ci.yml#L242-L243)

You would need to remove the cfg from [inside the tests.](https://github.com/rust-lang/portable-simd/blob/081240a6637c1dec77e5451e36dac4fe67773464/crates/core_simd/tests/masks.rs#L71-L82)

You should also remove the feature entirely from the crate, as it is used nowhere else.

**Comment by jorgecarleitao** [comment]
I think that the feature is still in use in another part of the crate (module `to_bytes`).

**Comment by workingjubilee** [comment]
Ah, you are right actually. I forgot about that.
Also for some reason altering the ci.yaml stopped the tests from running entirely...

**Comment by jorgecarleitao** [comment]
Sorry, that was a bad commit. Fixed it.

**Comment by workingjubilee** [comment]
???
...I have no idea what's wrong here.

**Comment by jorgecarleitao** [comment]
Closing in favor of  #238, since there is something going on with the CI in this one

**Pull request closed without merging**
