### PR TITLE
Removed need for generic_const_expr in bitmask

### LINKED ISSUE #223: Make `from/to_bitmask` not depend on `generic_const_exprs`
I.e. [these](https://github.com/rust-lang/portable-simd/blob/65cb2c90a0688c110d983a2dbb9932900cd6b5d9/crates/core_simd/src/masks/full_masks.rs#L115) are under `generic_const_exprs` which will take some time to stabilize.

Goal: find a way of re-writing those two functions without using `generic_const_exprs`

### PR DESCRIPTION
**Pull request by jorgecarleitao**
Closes #223

### CODE REVIEW

**Comment by workingjubilee** [comment]
Problem is: GitHub itself. Cool.
https://www.githubstatus.com/

**Comment by calebzulawski** [comment]
I should mention I took a stab at a more complete solution for this in the `feature/better-bitmask` branch, but was blocked by an unusual const generics issue at the time (no clue if that's still the case)

**Comment by calebzulawski** [comment]
I just posted #239 with the changes I was talking about, we can compare these two PRs.

**Comment by jorgecarleitao** [comment]
fwiw, I am fine with any. This is hopefully the last blocking issue forbiding arrow2 from adopting portable-simd. So either PR is fine - I would just like to give this a spin without the major performance regression vs packed_simd.

**Comment by workingjubilee** [comment]
Resolved in #239.

**Pull request closed without merging**
